### ISSUE TITLE
Create docs for Cloud Feature - Custom Attributes

### ISSUE THREAD

**Issue by evtk** [sodadata/docs#154]
We will release the Custom Attributes feature in Q1-22, due date is end of February but development is aimed to be finished somewhere first/second week of February. 

We want to provide our customers with a comprehensive documentation set on the subject of Custom Attributes. Special attention is required since:

Taken from the [Slite specs](https://sodadata.slite.com/app/channels/3F5HDIlx4V/notes/AU7zi9lhS6):
_Custom Attributes create great flexibility for our users. They no longer have to solely rely on the attributes provided by Soda, which gives them more power when it comes to grouping and filtering their resources._

_At the same time custom attributes can open the doors to potential problems. Problems which will likely arise from users 'abusing' the concept, or people from within Soda misunderstanding the usage of custom attributes. Below is an attempt on setting expectations straight so everyone knows what to expect from Custom Attributes and most importantly what not._

**Tasks:**

Create a new entry `Custom Attributes` under `Soda Cloud` in our docs: 
- [ ] explaining the concept of Custom Attributes in Soda Cloud
- [ ] explaining when to use and when **not** use Custom Attributes
- [ ] provide step by step guidance on how to create, modify, delete custom attributes on the Custom Attributes tab (organization level)
- [ ] provide step by step guidance on how to utilize assigned Custom Attributes in the Dataset update Dialog.

Provide copy for the Cloud platform, currently in scope:
- [ ] copy for the Custom Attributes `delete` flow, explaining the consequences of deleting a Custom Attribute
- [ ] ...
